import { jsPDF } from 'jspdf';
import { Classroom, Student, RecitationEvent } from '../types';

export function generateClassroomPdf(classroom: Classroom, sessionLogs?: RecitationEvent[]) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Helper colors
  const primaryColor = { r: 15, g: 23, b: 42 }; // slate-900
  const secondaryColor = { r: 71, g: 85, b: 105 }; // slate-600
  const accentColor = { r: 245, g: 158, b: 11 }; // gold/amber-500
  const lightBgColor = { r: 248, g: 250, b: 252 }; // slate-50
  const borderColor = { r: 226, g: 232, b: 240 }; // slate-200

  let currentY = 15;

  const checkPageOverflow = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - 15) {
      doc.addPage();
      currentY = 15;
      drawFooter();
      return true;
    }
    return false;
  };

  const drawFooter = () => {
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      `Generated by Recitation Tracker | Page ${doc.internal.pages.length - 1}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  };

  // --- HEADER ---
  // Top thick colored accent bar
  doc.setFillColor(accentColor.r, accentColor.g, accentColor.b);
  doc.rect(0, 0, pageWidth, 5, 'F');

  // App Title
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(accentColor.r, accentColor.g, accentColor.b);
  doc.text('RECITATION ACADEMIC REPORT', 14, currentY);
  currentY += 6;

  // Classroom & Subject Name
  doc.setFontSize(22);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(classroom.name.toUpperCase(), 14, currentY);
  currentY += 8;

  if (classroom.subject) {
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
    doc.text(`Subject: ${classroom.subject}`, 14, currentY);
    currentY += 6;
  }

  // Date
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  const dateStr = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.text(`Report Date: ${dateStr}`, 14, currentY);
  currentY += 10;

  // Decorativedivider
  doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  doc.line(14, currentY, pageWidth - 14, currentY);
  currentY += 10;

  // --- STATS OVERVIEW CARDS (3 columns) ---
  const studentsCount = classroom.students.length;
  const totalPoints = classroom.students.reduce((acc, s) => acc + s.points, 0);
  const avgPoints = studentsCount > 0 ? (totalPoints / studentsCount).toFixed(1) : '0.0';
  const highestPoints = studentsCount > 0 ? Math.max(...classroom.students.map(s => s.points)) : 0;
  const topStudent = classroom.students.find(s => s.points === highestPoints)?.name || 'N/A';

  const cardWidth = (pageWidth - 28 - 8) / 3;
  const cardHeight = 22;

  // Card 1: Students & Total Participation
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(14, currentY, cardWidth, cardHeight, 'F');
  doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  doc.rect(14, currentY, cardWidth, cardHeight, 'S');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('CLASS SIZE & POINTS', 18, currentY + 6);
  doc.setFontSize(12);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`${studentsCount} Students / ${totalPoints} Pts`, 18, currentY + 14);

  // Card 2: Averages
  const card2X = 14 + cardWidth + 4;
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(card2X, currentY, cardWidth, cardHeight, 'F');
  doc.rect(card2X, currentY, cardWidth, cardHeight, 'S');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('AVERAGE POINTS', card2X + 4, currentY + 6);
  doc.setFontSize(12);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`${avgPoints} points/student`, card2X + 4, currentY + 14);

  // Card 3: Top Performer
  const card3X = card2X + cardWidth + 4;
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(card3X, currentY, cardWidth, cardHeight, 'F');
  doc.rect(card3X, currentY, cardWidth, cardHeight, 'S');
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('MVP / TOP RECITATION', card3X + 4, currentY + 6);
  doc.setFontSize(10);
  doc.setTextColor(accentColor.r, accentColor.g, accentColor.b);
  doc.text(`${topStudent.substring(0, 16)} (${highestPoints} pts)`, card3X + 4, currentY + 14);

  currentY += cardHeight + 12;

  // ---STUDENTS LEADERBOARD TABLE ---
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text('Student Performance Standings', 14, currentY);
  currentY += 6;

  // Table header
  doc.setFillColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.rect(14, currentY, pageWidth - 28, 8, 'F');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text('Rank', 18, currentY + 5.5);
  doc.text('Student Name', 35, currentY + 5.5);
  doc.text('Attendance', 100, currentY + 5.5);
  doc.text('Active Streak', 135, currentY + 5.5);
  doc.text('Total Recitation Points', pageWidth - 18, currentY + 5.5, { align: 'right' });

  currentY += 8;

  // Sort students by points descending
  const sortedStudents = [...classroom.students].sort((a, b) => b.points - a.points);

  sortedStudents.forEach((student, index) => {
    checkPageOverflow(8);

    // Row zebra background
    if (index % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(14, currentY, pageWidth - 28, 8, 'F');
    }

    // Border line at the bottom
    doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
    doc.line(14, currentY + 8, pageWidth - 14, currentY + 8);

    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(51, 65, 85); // slate-700

    // Rank
    doc.text(`#${index + 1}`, 18, currentY + 5.5);

    // Bold first 3 ranks
    if (index < 3) {
      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(accentColor.r, accentColor.g, accentColor.b);
    } else {
      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
    }

    // Name
    doc.text(student.name, 35, currentY + 5.5);

    // Attendance
    doc.setFont('Helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const statusText = student.attendance.substring(0, 1).toUpperCase() + student.attendance.substring(1);
    doc.text(statusText, 100, currentY + 5.5);

    // Streak
    const streakStr = student.streak > 0 ? ` 🔥 ${student.streak} days` : '0 days';
    doc.text(streakStr, 135, currentY + 5.5);

    // Total points
    doc.setFont('Helvetica', 'bold');
    doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
    doc.text(`${student.points} pts`, pageWidth - 18, currentY + 5.5, { align: 'right' });

    currentY += 8;
  });

  currentY += 10;

  // --- RECENT RECITATION LOGS ---
  const logsToRender = sessionLogs || classroom.history;
  if (logsToRender && logsToRender.length > 0) {
    checkPageOverflow(20);

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
    doc.text('Session Recitation Event History', 14, currentY);
    currentY += 6;

    // Header logs
    doc.setFillColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
    doc.rect(14, currentY, pageWidth - 28, 8, 'F');

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text('Time', 18, currentY + 5.5);
    doc.text('Student Name', 45, currentY + 5.5);
    doc.text('Activity / Notes', 95, currentY + 5.5);
    doc.text('Score', pageWidth - 18, currentY + 5.5, { align: 'right' });

    currentY += 8;

    // Render newest events first
    const sortedLogs = [...logsToRender].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());

    sortedLogs.slice(0, 15).forEach((log, index) => {
      checkPageOverflow(8);

      if (index % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(14, currentY, pageWidth - 28, 8, 'F');
      }

      doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
      doc.line(14, currentY + 8, pageWidth - 14, currentY + 8);

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);

      // Simple time formatting
      const t = new Date(log.timestamp);
      const timeStr = t.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      doc.text(timeStr, 18, currentY + 5.5);

      // Student name
      doc.setFont('Helvetica', 'semibold');
      doc.text(log.studentName, 45, currentY + 5.5);

      // Reason / Context
      doc.setFont('Helvetica', 'normal');
      doc.text((log.reason || 'Slipped recitation session').substring(0, 50), 95, currentY + 5.5);

      // Score
      doc.setFont('Helvetica', 'bold');
      const prefix = log.pointsAwarded >= 0 ? '+' : '';
      if (log.pointsAwarded >= 0) {
        doc.setTextColor(22, 163, 74);
      } else {
        doc.setTextColor(220, 38, 38);
      }
      doc.text(`${prefix}${log.pointsAwarded} pts`, pageWidth - 18, currentY + 5.5, { align: 'right' });

      currentY += 8;
    });
  }

  // Draw final page numbers
  drawFooter();

  // Save pdf
  doc.save(`${classroom.name.toLowerCase().replace(/\s+/g, '_')}_grades.pdf`);
}
