import { jsPDF } from 'jspdf';
import { ClassSession } from '../types';

export function generateSessionPdf(session: ClassSession) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Color theme guidelines - Slate-900 & Indigo-600 & Amber-500
  const primaryColor = { r: 15, g: 23, b: 42 }; // slate-900
  const secondaryColor = { r: 71, g: 85, b: 105 }; // slate-600
  const accentColor = { r: 79, g: 70, b: 229 }; // indigo-600
  const highlightColor = { r: 245, g: 158, b: 11 }; // gold/amber-500
  const lightBgColor = { r: 248, g: 250, b: 252 }; // slate-50
  const borderColor = { r: 226, g: 232, b: 240 }; // slate-200

  let currentY = 15;

  const checkPageOverflow = (neededHeight: number) => {
    if (currentY + neededHeight > pageHeight - 15) {
      doc.addPage();
      currentY = 15;
      drawFooter();
      return true;
    }
    return false;
  };

  const drawFooter = () => {
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(
      `Class Session Stats Report | Generated by RecitaTrack Pro | Page ${doc.internal.pages.length - 1}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  };

  // Top accent bar
  doc.setFillColor(accentColor.r, accentColor.g, accentColor.b);
  doc.rect(0, 0, pageWidth, 5, 'F');

  // Document Tagline
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(accentColor.r, accentColor.g, accentColor.b);
  doc.text('LIVE CLASS SESSION SUMMARY REPORT', 14, currentY);
  currentY += 6;

  // Title: Class Name
  doc.setFontSize(22);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(session.className.toUpperCase(), 14, currentY);
  currentY += 8;

  // Subject if present
  if (session.subject) {
    doc.setFont('Helvetica', 'normal');
    doc.setFontSize(12);
    doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
    doc.text(`Subject Area: ${session.subject}`, 14, currentY);
    currentY += 6;
  }

  // Session timing details
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  
  const startLocalStr = new Date(session.startTime).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const startTimeLocalHour = new Date(session.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  const endTimeLocalHour = new Date(session.endTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

  doc.text(`Date: ${startLocalStr} | Timeframe: ${startTimeLocalHour} - ${endTimeLocalHour} (${session.duration})`, 14, currentY);
  currentY += 10;

  // Horizontal separator
  doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  doc.line(14, currentY, pageWidth - 14, currentY);
  currentY += 10;

  // --- STATISTICS GRID PANEL ---
  const colWidth = (pageWidth - 28 - 8) / 3;
  const colHeight = 22;

  // Card 1: Attendance & Scope
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(14, currentY, colWidth, colHeight, 'F');
  doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  doc.rect(14, currentY, colWidth, colHeight, 'S');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('ENGAGED ATTENDANCE', 18, currentY + 6);
  doc.setFontSize(12);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`${session.studentsCount} Present Students`, 18, currentY + 14);

  // Card 2: Recitation Actions Total
  const card2X = 14 + colWidth + 4;
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(card2X, currentY, colWidth, colHeight, 'F');
  doc.rect(card2X, currentY, colWidth, colHeight, 'S');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('TOTAL RECITATIONS', card2X + 4, currentY + 6);
  doc.setFontSize(12);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`${session.eventsCount} Events / +${session.pointsAwarded} Pts`, card2X + 4, currentY + 14);

  // Card 3: MVP highlight
  const card3X = card2X + colWidth + 4;
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(card3X, currentY, colWidth, colHeight, 'F');
  doc.rect(card3X, currentY, colWidth, colHeight, 'S');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('SESSION OUTSTANDING MVP', card3X + 4, currentY + 6);
  
  doc.setFontSize(10);
  doc.setTextColor(highlightColor.r, highlightColor.g, highlightColor.b);
  if (session.mvpName && session.mvpPointsGained > 0) {
    let rawLabel = `${session.mvpName} (+${session.mvpPointsGained} Pts)`;
    if (rawLabel.length > 25) {
      doc.setFontSize(8); // smaller font size for longer combined names
      if (rawLabel.length > 36) {
        rawLabel = rawLabel.substring(0, 33) + '..';
      }
    } else {
      doc.setFontSize(9.5);
    }
    doc.text(rawLabel, card3X + 4, currentY + 14);
  } else {
    doc.text('No Events Recorded', card3X + 4, currentY + 14);
  }

  currentY += colHeight + 6;

  // --- SUB-METRICS DETAIL TABLE PANEL ---
  doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
  doc.rect(14, currentY, pageWidth - 28, 22, 'F');
  doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
  doc.rect(14, currentY, pageWidth - 28, 22, 'S');

  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  
  // Left aligned: Attendance breakdown
  doc.text('ROLL-CALL PROFILE STATUSES', 18, currentY + 5);
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`Present: ${session.studentsCount || 0}    |    Late: ${session.lateCount ?? 0}    |    Absent: ${session.absentCount ?? 0}    |    Excused: ${session.excusedCount ?? 0}`, 18, currentY + 10);

  // Right aligned: Engagement breakdown
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text('ENGAGEMENT METRICS & ACTIONS', (pageWidth / 2) + 14, currentY + 5);
  
  doc.setFont('Helvetica', 'normal');
  doc.setFontSize(8.5);
  doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
  doc.text(`Rate: ${session.engagementRate ?? 0}% (engaged: ${session.uniqueParticipantsCount ?? 0} studs)    |    Spins: ${session.spinWheelWinnersCount ?? 0}    |    Groups: ${session.groupGradingsCount ?? 0}`, (pageWidth / 2) + 14, currentY + 10);

  // Bottom subtitle: status ratio
  doc.setFont('Helvetica', 'bold');
  doc.setFontSize(7.5);
  doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
  doc.text(`Ratio: +${session.positiveEventsCount ?? 0} rewards / -${session.negativeEventsCount ?? 0} corrections`, 18, currentY + 17);

  currentY += 22 + 10;

  // --- RECITATION LOGS LIST ---
  const events = session.events || [];
  if (events.length > 0) {
    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
    doc.text('Chronological Recitation Events Logged', 14, currentY);
    currentY += 6;

    // Header structure
    doc.setFillColor(primaryColor.r, primaryColor.g, primaryColor.b);
    doc.rect(14, currentY, pageWidth - 28, 8, 'F');

    doc.setFont('Helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(255, 255, 255);
    doc.text('Time', 18, currentY + 5.5);
    doc.text('Student Name', 45, currentY + 5.5);
    doc.text('Recitation Event Detail / Remarks', 95, currentY + 5.5);
    doc.text('Gained', pageWidth - 18, currentY + 5.5, { align: 'right' });

    currentY += 8;

    events.forEach((log, index) => {
      checkPageOverflow(8);

      if (index % 2 === 1) {
        doc.setFillColor(248, 250, 252);
        doc.rect(14, currentY, pageWidth - 28, 8, 'F');
      }

      doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
      doc.line(14, currentY + 8, pageWidth - 14, currentY + 8);

      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(8.5);
      doc.setTextColor(71, 85, 105);

      const logTime = new Date(log.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      doc.text(logTime, 18, currentY + 5.5);

      doc.setFont('Helvetica', 'bold');
      doc.setTextColor(primaryColor.r, primaryColor.g, primaryColor.b);
      doc.text(log.studentName, 45, currentY + 5.5);

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      doc.text((log.reason || 'Active Class Participation').substring(0, 52), 95, currentY + 5.5);

      doc.setFont('Helvetica', 'bold');
      if (log.pointsAwarded >= 0) {
        doc.setTextColor(22, 163, 74); // green
        doc.text(`+${log.pointsAwarded} pts`, pageWidth - 18, currentY + 5.5, { align: 'right' });
      } else {
        doc.setTextColor(220, 38, 38); // red
        doc.text(`${log.pointsAwarded} pts`, pageWidth - 18, currentY + 5.5, { align: 'right' });
      }

      currentY += 8;
    });
  } else {
    // Empty session log notice
    doc.setFillColor(lightBgColor.r, lightBgColor.g, lightBgColor.b);
    doc.rect(14, currentY, pageWidth - 28, 20, 'F');
    doc.setDrawColor(borderColor.r, borderColor.g, borderColor.b);
    doc.rect(14, currentY, pageWidth - 28, 20, 'S');

    doc.setFont('Helvetica', 'italic');
    doc.setFontSize(10);
    doc.setTextColor(secondaryColor.r, secondaryColor.g, secondaryColor.b);
    doc.text('No active grading or recitation events were triggered during this live class.', pageWidth / 2, currentY + 11, { align: 'center' });
  }

  // Draw final footer elements
  drawFooter();

  // Trigger PDF file download
  const formattedClass = session.className.toLowerCase().replace(/\s+/g, '_');
  const sessionTimeString = new Date(session.startTime).toISOString().split('T')[0];
  doc.save(`session_summary_${formattedClass}_${sessionTimeString}.pdf`);
}
